### ISSUE TITLE
You paper in AIIDE 2018 claims that MKULTRA is Open Source but I can't find a license anywhere

### ISSUE THREAD

**Issue by DrAlta** [ianhorswill/MKULTRA#13]
Could you add a readme.md with a license?

BTW: I'm interested in adapting MKULTRA into a Language teaching tool.

It's a my IAL project so the Language can be adapted to fit the technical/programming constraints of the game.

I'll be using Godot not Unity. so the first thing is to port/clone MKULTRA to Godot.

Are/will you(Ian) be availed for hire. I have 100USD month I'll have the $2000 from the Covid relief. I'm lucky I only lost $80 of disposable income a month from the lockdown.

**Comment by ianhorswill** [comment]
It's MIT license.  You can do with it what you like, save for claiming authorship of the original code.  I'm happy to do finite amounts of consulting for free.  It would be nice to see some kind of uptake of it.  But I really want to warn you that which MKULTRA was a technical success and showed there's a lot of interesting stuff you can do with 1980s symbolic AI technology, it was a complete failure as a game.  I sent you a link to a paper on its playability issues in email.  It was published in AIIDE 18.

**Comment by DrAlta** [comment]
It's failed as a game because you tried to preserve the illusion that humans aren't clockwork.  

Human are clockwork and they Diabolically simple clockwork.  So simple that many are unable to wrap their mind around it.  Their cognitive processes find it positively repulsive, yet with careful analysis it is proven to be fundamentally and logically sound. 

 "Sì, abbiamo un'anima. Ma è fatta di tanti piccoli robot – "Yes, we have a soul, but it’s made of lots of tiny robots."  Neurology tells us that, and the unreasonable effectiveness of deep neuro learning proved that Neurology was right.

I want to make serious game that teacher people to view the 'other' not as demons to be killed but as puzzles to be solved.
